theme: jekyll-theme-minimal
title: Lily's Data Science Portfolio!
description: Hello. I am currently a University of Washington student studying data science. This platform page is where I plan to exhibit my projects! [Contact me](https://github.com/lil-ds/lil-ds.github.io/blob/77063e295ffb62e5abcc47663aa5b8ab3ba1cdc6/contact-me.md)
